### ISSUE TITLE
Agree on tech stack, file structure and eslint

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/nightingale#10]
Please put in here you're preferred frameworks to be used.

**Comment by RamyAlshurafa** [comment]
Front-end:
* React / Redux
* styled-components

Back-end:
Express

Database:
MongoDB

Testing:
* Jest / Enzyme

**Comment by AsalaKM** [comment]
### Front-End
- React.js
- D3 (data visualization)
- Styled component

### Data Base
- Mongo database

### Back-End
- Express.js

**Comment by RamyAlshurafa** [comment]
**dialogflow**
https://console.dialogflow.com/api-client/

**watson**
https://www.ibm.com/watson/developercloud/

**Comment by thejoefriel** [comment]
Thanks @RamyAlshurafa - my initial preference would be dialogflow as we have a team that already used it here and they really liked it - plus we can ask them questions if any issues.

**Comment by thejoefriel** [comment]
**Front-end:**

React 
styled-components
tachyons

**Back-end:**

Express

**Database:**

MongoDB or postrgeSQL

**Testing:**

Jest / Enzyme

**Comment by thejoefriel** [comment]
@AsalaKM Have you used D3 before? 
@RamyAlshurafa Have you used socket.io before?

Haven't used either of these, and very happy to try :) Would be great to learn more about it

**Comment by AsalaKM** [comment]
@thejoefriel,
yes, I used it before when I was work on my last project.

**Comment by thejoefriel** [comment]
OK great @AsalaKM 
That's fine too @RamyAlshurafa - what does socket.io primarily do?

**Comment by thejoefriel** [comment]
Also @RamyAlshurafa @dupreesi @AsalaKM , can we agree folder structure and deployment in this issue please? I've edited it accordingly. 

Are we planning to use Create-React-App to set up react?
If so, to keep things simple, I'm thinking we deploy on heroku, and we use the same folder structure that we had for ![Connect 5](https://github.com/techforbetter/connect5). 

What does everyone else think?

**Comment by dupreesi** [comment]
Front-end:
React 
styled-components
Tachyons

Back-end:
Express

Database:
Ideally going back to SQL queries but would be fine with either SQL or Mongo depending on the group decision

Testing:
Jest / React Testing Library

**Comment by dupreesi** [comment]
@RamyAlshurafa @AsalaKM haven't used socket/ d3 so would be up for embedding some new stuff

@thejoefriel i think the connect5 setup was good enough to be re=used :)

**Comment by dupreesi** [comment]
@RamyAlshurafa @AsalaKM haven't used socket/ d3 so would be up for embedding some new stuff

@thejoefriel i think the connect5 setup was good enough to be re=used :)

**Comment by RamyAlshurafa** [comment]
regarding `Socket`,
but I think, we can run the app without using `socket`, if you took a look at the flow chart you will find that the client side always who start the conversation. and each question comes from the bot will be sent when the client side sends the previous user's reply, the socket will be used if the server side wants to send anything for the client side, not in our case
but if you agree to use it I can read and try it this weekend.
And yes I agree with @dupreesi that connect5 was good enough to reuse it.

**Comment by thejoefriel** [comment]
Cool! Sounds like we're all agreed with the major points of set up. 

On eslint, generally you prefer airbnb config don't you? I'm fine with this as long as we can ensure we're using 2 spaces for spacing and double quotes across server and client just to keep things consistent? Also that we have eslint prettier put in place. Does that work for everyone? This is the set up we had for myPickle which worked nicely:

server:
```
{
  "extends": ["airbnb-base", "prettier"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": ["error"],
    "no-underscore-dangle": [
      2,
      {
        "allow": ["_id"]
      }
    ]
  }
}
```

client: 
```
{
  "extends": ["react-app", "prettier", "prettier/flowtype", "prettier/react"],
  "plugins": ["flowtype", "react", "prettier"],
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "node": true
  },
  "rules": {
    "prettier/prettier": "error"
  }
}
```
and then the modules "eslint-config-prettier", "eslint-plugin-prettier" etc

Does that work for everyone?

**Comment by RamyAlshurafa** [comment]
for me looks good.
also if we forgot anything we can open an issue and modify things after all the team be happy with.

**Comment by thejoefriel** [comment]
Sounds good! On that basis I'm closing this issue now :)
