### ISSUE TITLE
Product Handover

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#112]
Hi @georgemetcalfe95 @aaronajohn 

Everything is going well and looking forward to showing you the full demo next week 👍 
At the moment we're all just deep in the code getting the features finalised and ironing out bugs. 

In terms of the product handover, is there any chance you would be free next Wednesday instead please? Any time from 10am to 2pm would work. 

No worries if not!

**Comment by aaronajohn** [comment]
Hey Joe,

I don't think that we will be available for the Wednesday, really sorry. We
are only free the Monday and Tuedays, normally i would be able to move
things around but the next week is hellish.

Aaron




[image: photo]
*Aaron John*
Co-Founder, Nightingale Software
07479540681 | aaron.john@wearenightingale.co.uk | www.wearenightingale.co.uk
 | Skype: aaronajohn <https://mail.google.com/mail/u/3/#>
<http://www.facebook.com/nightingalesoftware>
<http://twitter.com/talknightingale>
<http://www.linkedin.com/in/aaronajohn/>

**Comment by thejoefriel** [comment]
No worries! we'll stick with the time we have on monday :)
