### ISSUE TITLE
Few user stories / features to discuss

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#12]
There are a few issues it would be good to discuss. Please can everyone let me know what they think by leaving comments below:

- Should we potentially make the user view the explanation of service before they register rather than instantly after? This is because they are young students and so it is important to explain what the service is before they register

- Do we want to put them straight to a log in page when they register or sign them in when they register?

- Bio tab - do we actually need this in core? What would it include? We probably just get information from the chat(s) and store this in a database

- When the user logs in should the user go straight into chat or go to a dashboard? Potentially as a chat app, we could always send them straight to the chat, but then the navbar would let them move to other sections (e.g. Sessions, Mood chart)

- I've included two user journeys in the HackMD - does this cover them all?

**Comment by AsalaKM** [comment]
- I think we should put the explanation of services before they register. When they open the App they should know what they can benefit from it.

- After they register we can put them straight to the initial onboarding process page to give the key info about them, then put them straight to the login page to make a login.

- Bio tab -  actually we need this in core, it can include the  key info about the student (at least just for view in the core).

- When the user logs in he should go to a dashboard, then we can show a fixed button in all of the pages that can go straight into chat. And the navbar would let them move to main sections (Bio, Conversations and Mood chart)

**Comment by RamyAlshurafa** [comment]
**explanation of service**
I agree with making it before registering, so they can understand the app.

**regarding redirect to the login page or log them in**
I think log them in is better so we cut through one step.

all the rest points think its okay how does it come
