### ISSUE TITLE
chatbot goes wild

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/nightingale#121]
it refreshes itself every few minutes
<img width="537" alt="bildschirmfoto 2019-02-13 um 09 50 28" src="https://user-images.githubusercontent.com/23721486/52698984-fd116c00-2f74-11e9-910b-0c0874fc38eb.png">

**Comment by dupreesi** [comment]
maybe thats because we are all using the same channel or so...

**Comment by thejoefriel** [comment]
I believe I've fixed this with #127 as they were related issues so closing this for now
