### ISSUE TITLE
Question about Service Explanation

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#22]
Hi @aaronajohn @georgemetcalfe95 , we have a question on when it would be best to do a short explanation of the service (this would most likely be done in a series of c. 3 cards as you often see in an onboarding process). 

Since we're dealing with students and mental health, should we make them read through the explanation before they register? 

Or does this not matter and instead you'd prefer them to get a bit more explanation once they're registered?

**Comment by aaronajohn** [comment]
Hey Joe!

I think that it would be better to get an explanation after they
register...

Aaron

**Comment by thejoefriel** [comment]
Thanks @aaronajohn - we'd recommend still having some explanation of the service beforehand so they know what they're signing up to (otherwise there's no incentive to sign up), but then we can do a fuller explanation once they've registered. What do you think?

**Comment by thejoefriel** [comment]
@aaronajohn  also - would you be able to send us a description that explains the services please. This copy is important for us to put into the design prototype

**Comment by aaronajohn** [comment]
Not a problem! We can get that over to you. We are both at our other jobs
today, so all this will be later on. Really sorry.

Aaron

**Comment by thejoefriel** [comment]
@aaronajohn no worries! Will keep an eye out

**Comment by georgemetcalfe95** [comment]
Hey @thejoefriel - I would agree with you that there needs to be a short description before they register. Possibly something like: 

"Hey! I'm Nightingale, a personal buddy to help you enjoy school." 

I like the idea of the subsequent description being split across three screens. They could be: 

1) I'm here for you, whatever we talk about will be kept between us. Sound good? 
2) I'm going to help you by asking you how you feel about things that happen in your day, and you can talk to me about anything else on your mind. 
3) By answering these questions and talking to me, we can try to figure out how to make your time at school better :D

**Comment by thejoefriel** [comment]
Thanks for this @georgemetcalfe95 sounds good! At the moment we've put these sentences in the initial chatbot conversation as a nice way to get them used to this being a chat
