### ISSUE TITLE
Do we need a bio for the user on their dashboard?

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#25]
Hi @aaronajohn @georgemetcalfe95 - one more question. Do we need a bio section on the user's dashboard (e.g. an overview of some of the key information such as favourite subject etc). Not sure if we want the user to be able to see these things or whether it's unnecessary and more about the conversation with the chat bot and then hopefully showing them trends via mood per day etc. What do you think?

**Comment by aaronajohn** [comment]
Hey!
Yeah I feel that it is a little unnecessary. So it should be fine. I feel
if they want to amend it that should be an option.

Aaron.

**Comment by thejoefriel** [comment]
Ok great thanks!
