### ISSUE TITLE
I get a message if I write a keyword that suggests I need immediate support

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#32]
Relates #14 

Text detection for certain keywords (e.g. suicide) to prompt the user to speak to a real person

- [x] List of words to look out for in conversations
- [x] Scan each user input for these words
- [x] If word is detected load pop up box telling them to contact someone immediately

**Comment by thejoefriel** [comment]
@aaronajohn @georgemetcalfe95 - hey! are you able to provide a list of emergency words we should look out for please?

**Comment by aaronajohn** [comment]
Hey Joe,

We are meeting tonight after work we will add this to the things to send
over alongside the other flow/s

Cheers,
Aaron

[image: photo]
*Aaron John*
Co-Founder, Nightingale Software
07479540681 | aaron.john@wearenightingale.co.uk | www.wearenightingale.co.uk
 | Skype: aaronajohn <https://mail.google.com/mail/u/3/#>
<http://www.facebook.com/nightingalesoftware>
<http://twitter.com/talknightingale>
<http://www.linkedin.com/in/aaronajohn/>

**Comment by thejoefriel** [comment]
Awesome thanks @aaronajohn !

**Comment by aaronajohn** [comment]
Hey Joe!

I am sending over the flows on the other channel! Me and George had a chat,
we feel that we would not be able to be confident in sending in a list that
we have made. We have contacted the Childrens society about this as we
believe that they have such a list. It may be a few days before we hear
back from them, hope this is not a massive problem! Let me know your
thoughts.

Cheers,
Aaron

[image: photo]
*Aaron John*
Co-Founder, Nightingale Software
07479540681 | aaron.john@wearenightingale.co.uk | www.wearenightingale.co.uk
 | Skype: aaronajohn <https://mail.google.com/mail/u/3/#>
<http://www.facebook.com/nightingalesoftware>
<http://twitter.com/talknightingale>
<http://www.linkedin.com/in/aaronajohn/>

**Comment by thejoefriel** [comment]
OK @aaronajohn no worries. We'll do a template one for now so we can build the functionality and then can put in the words once you have them. Ideally if you can get them by Wednesday latest, then we'll have time to get them in. :)

**Comment by aaronajohn** [comment]
Ok that sounds good, ill keep you up to date as to what happens! Cheers

[image: photo]
*Aaron John*
Co-Founder, Nightingale Software
07479540681 | aaron.john@wearenightingale.co.uk | www.wearenightingale.co.uk
 | Skype: aaronajohn <https://mail.google.com/mail/u/3/#>
<http://www.facebook.com/nightingalesoftware>
<http://twitter.com/talknightingale>
<http://www.linkedin.com/in/aaronajohn/>
