### ISSUE TITLE
Supply brand assets

### ISSUE THREAD

**Issue by aaronajohn** [techforbetter/nightingale#4]
Logo 
photos
colours

**Comment by thejoefriel** [comment]
@aaronajohn @georgemetcalfe95 - do you think you'll be able to send this across later today please?

**Comment by aaronajohn** [comment]
![image 2](https://user-images.githubusercontent.com/46899143/51620012-692a2280-1f29-11e9-81c4-8a3a7854d137.png)

**Comment by aaronajohn** [comment]
In terms of colours go crazy! The logo has our colours in it. So use what you feel works.

**Comment by aaronajohn** [comment]
Let me know if there is anything else you need on this

**Comment by aaronajohn** [comment]
Font we use is **Proxima Nova**

**Comment by thejoefriel** [comment]
Amazing @aaronajohn ! Thanks for this. 

@RamyAlshurafa @AsalaKM @dupreesi - let's incorporate this into the Figma prototype today 👍
