### ISSUE TITLE
Agree database schema

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#44]
Please try building models and paste in here along with your thinking

**Comment by RamyAlshurafa** [comment]
**User**:
```js
{
  username: string,
  name: string,
  password: string,
  gender: string,
  age: number,
  school: string,
  calss: string
  ...
}
```


**conversation**:
```js
{
  user: ref(userId),
  time: timestamp,
  moodEmoji: string // or we can make it as ref from emojis table,
  isCompleted: boolean // if the user answer all questions for the conversation this would be true, otherwise, it would be false
}
```


**question**
```js
{
  questionType: string // basic info Or daily conversation,
  text: string,
  options: [
    {
      text: string,
      nextQuestion: ref(question ID),
      isOpenText: boolean
    }
  ]
}
```

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa I think overall this looks great! Really good 👍 😄 

Couple of quick things:

- I think we need a "requiresReply: boolean" field in the question table, just so we know explicitly if we should wait for a user input or automatically render the next question

- The text for each question perhaps should be an array. That way, we can put variations of the same question (e.g. ["Awesome", "That's great!", "Amazing!"]) and then when we render question, check if the array length is longer than 1. If so, then randomly pick one of the strings. This way we easily provide variation within these questions. What do you think?

- I agree we should have a separate emojis table. That way we can store more details for each emoji:
```
{
   moodEmoji: string
   moodDescrip: string // this would be the word that we apply to this emoji e.g. angry, sad, stressed
   score: number // this would allow us to create averages. So for example we could show the average 
 moodEmoji for each of their Friday conversations
}
```

- Let's remove gender. I don't think that's information we need to store about the student and can get into tricky areas about what they identify as and if they want to disclose this

**Comment by dupreesi** [comment]
Yeah really good. One thing to consider before we get into more details: 
are we using any third party conversation software? dialogflow is the one to use as it is free and said to be 'easy' to implement with node. I did some research and linked some stuff here https://github.com/techforbetter/nightingale/issues/11

main question: are we/ how are we integrating dialogflow and the schemas?

**Comment by RamyAlshurafa** [comment]
@thejoefriel  yeah I agree with you, good spots
 @dupreesi mmm I'm really not sure.
do we need to make it an open chat with the bot (friendly chat)? so the student can chat with it anytime, or we need to get answers to specific questions from the student?
* if open chat: yes we need dialogflow.
* if specific questions: I think no.

this is my thought maybe I'm wrong :sweat_smile:

**Comment by dupreesi** [comment]
so to make the app future-proof and more interesting/ dynamic we could actually use dialogflow as our chat-framework and use something thats called Fullfillments which means you can embed code to alter the api/webhook getting and posting data from/to dialogflow. I found some stuff online but it seems to be quite tricky. however, once its been set up dailogflow could be an amazing thing because we could train it, the product owners could actually further develop it and so on.... 
here is an introduction to Fullfillments from the dialogflow docs
https://dialogflow.com/docs/getting-started/integrate-services
not sure if we can try to use it or if its too hard. 
maybe have a look @RamyAlshurafa and @AsalaKM on Sunday?

**Comment by dupreesi** [comment]
https://github.com/dialogflow/fulfillment-firestore-nodejs

a starting point for anyone looking to connect a database to their Dialogflow agent and can be expanded to store users preferences, retrieve relevant data from your systems or enable your users to collaborate via chat/voice.

**Comment by RamyAlshurafa** [comment]
@dupreesi Thank you.
Im working on right now and on Monday I will share with you what I did. so we can agree on that.

**Comment by thejoefriel** [comment]
@RamyAlshurafa this all looks really good to me. Happy to go with this for now. Keen to hear why we don't need to store anything on questions, but yeah overall sounds good :)

Everyone else happy? @dupreesi @AsalaKM

**Comment by thejoefriel** [comment]
This is agreed for now, so closing.
