### ISSUE TITLE
Agree PR requirements

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#45]
It would be good to agree essential criteria your PR must pass before it is ready for review. 
I've also then added below best practice criteria as well, if you have time. 

Let me know what you think!

## Essential checklist
These must be checked in order for a PR to be considered ready for review
- [ ] **Branch is up to date with master**
- **The project runs**
- - [ ] You can download and install locally, and run the project locally
- - [ ] All existing and new features run without bugs
- - [ ] The build script runs without error
- **Code is consistent**
- - [ ] Linter is used, no error messages
- - [ ] Code is consistent with agreed team style
- - [ ] Naming of files is consistent with project (e.g. all files named with camelCase)
- - [ ] If you have written tests, they are in the same folder as the original file, with the extension .test.js
- **No console logs**
- - [ ] Console.log is only used for crucial system messages (e.g. which port server is on).
- - [ ] Any console.logs used for debugging have been removed.
- - [ ] Console.error is used in error handling.

## Best practice checklist
If time is available, please try to ensure these are checked too. If you don't have time, or are struggling with any of them, then it is fine to raise the PR, but please just **create a new issue that covers what still needs to be done** so you can pick it up later or someone else can pick up on that if there's time
- [ ] **Tests are in place**
- - [ ] Test file is in the same folder as the original file, with the extension .test.js
- - [ ] Each new file written has a test file (where possible)
- [ ] **Tests all pass**
- - [ ] All tests should pass locally and on Travis
- - [ ] Edge cases have been considered in tests
- [ ] **Test coverage is maintained**
- - [ ] Project coverage stays > 95%
- - [ ] PR will not bring down coverage by more than 1%
- - [ ] Files and lines of code have been ignored if they cannot be tested
- - [ ] If you are stuck with writing tests, you have assigned @arrested-developer to the PR and added a comment to explain what help is needed

**Comment by thejoefriel** [comment]
Thanks. @RamyAlshurafa @AsalaKM - you happy with this suggested criteria?

**Comment by RamyAlshurafa** [comment]
@thejoefriel all is good
but who is the person will tick/check these points? QA or the person who raised the PR?

**Comment by thejoefriel** [comment]
@RamyAlshurafa it would need to be the person who raised the PR. It's just a useful way to remind us of what we need to do before we consider a PR to be ready. 
Whoever in the team then reviews can also make a comment if they've noticed one of the essential things hasn't been done.

**Comment by RamyAlshurafa** [comment]
make sense :+1:

**Comment by arrested-developer** [comment]
Please bear in mind that I'm going to be having a baby any day now, so I might not be able to respond to questions about testing. If I'm around though, I'm happy to! 👼🏼

**Comment by RamyAlshurafa** [comment]
@arrested-developer

**Comment by arrested-developer** [comment]
shukran!

**Comment by thejoefriel** [comment]
Good point @arrested-developer ! Will take you off from the essential list haha
