### ISSUE TITLE
Complete User Testing scripts

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#48]
- [ ] Write user testing scripts including tasks and questions
- [ ] Share hackmd here with team for review

**Comment by thejoefriel** [comment]
@AsalaKM @dupreesi @RamyAlshurafa 

The hackMD is [here](https://hackmd.io/O9S1z2D_RcqH6xhD3bJNBg?edit)

Let me know whether you're happy with this or would like any changes!

**Comment by RamyAlshurafa** [comment]
great job @thejoefriel  :+1: 
could we ask them if they used any chatbots before and if they are happy with chatting with bots?

**Comment by dupreesi** [comment]
great @thejoefriel and good addition @RamyAlshurafa

**Comment by thejoefriel** [comment]
Sounds good @RamyAlshurafa !
@AsalaKM - any thing else you think we should add?

**Comment by thejoefriel** [comment]
Closing this issue now as we're about to do the testing! :)

**Comment by thejoefriel** [comment]
We carried out today tests with 4 users.

Full HackMD can be read here: https://hackmd.io/O9S1z2D_RcqH6xhD3bJNBg?edit 

Will add each of the users' feedback below

**Comment by thejoefriel** [comment]
# User 1:
Year 10
Male
related apps: no
used chatbot before: once or twice
happy talking to bots: generally, but they can get repetitive with their answers

### Task 1
Please can you register on the app and complete your first conversation with the Nigthingale bot.
**no issues**

### Task 2
Please find resources for handling stress.
**rather use term useful advice than resources**

### Task 3
Please check out the conversation you had on the app on the 14th Jan
**no issues**

### Task 4
We would like you to see your overall average mood for each day of the week
**no issues**

### Task 5
Finally please log out
**no issues**

## Follow Up Questions

- How did you find using the application?
    - easy
- Did you have any other observations that you’d like to share?
    - involve sounds for incoming messages etc
- How comfortable are you talking to a bot about these issues? What would make you feel more comfortable?
    - should mention data privacy at start (or make it clearer)
- Knowing what the platform is looking to do, is there anything else you would want to make you use it?
     - involve rewards/points/hot streak for loggin in 
     - maybe see points of you and your friends
- Have you used any similar platforms or applications before?
    - No
- What would you think if the bot incorporated gifs and memes within the conversation?
    - yes good idea
- Do you have any further questions for us?
    - can you use on any device? 
    - if angry he may use it ... depends on mood

**Comment by thejoefriel** [comment]
# User 2:
Year 10
Female
related apps: timetable/ organiser app for subjects, school events etc
used chatbot like this before? no. Did not know what a chatbot was
happy talking to bots: Once explained, generally seemed ok with the idea of it. Understood it more and was happier as she interacted with the app 

### USER FLOW 1:

### Task 1
Please can you register on the app.
    - no issues


### Task 2
Please see a breakdown of your moods over the past 30 days. 
    -    Dashboard was misleading as a title... maybe use Stats instead

### Task 3
Please have a conversation with the nightingale chatbot.
    - no issues
    - more advise related to any problem you mention at the end of conversation would be good

### Task 4
Please can you please check out the conversation you had on the app on the 14th Jan
    - initially found it hard to find until she went to the menu
    - Prefers Conversations rather than Sessions

### Task 5
Finally please log out
 - no issues

**_NOTE: Generally as the user interacted with the app and learnt what it was doing, she seemed happier with it and how it all worked_**

## Follow Up Questions

- How did you find using the application?
    - simple and modern
    
- Did you have any other observations that you’d like to share?
    - would use the app when feeling down, maybe not when happy

- How comfortable are you talking to a bot about these issues? What would make you feel more comfortable?
    - Generally fine, but would want more advice of what to do with any problem I talk about

- Have you used any similar platforms or applications before?
    - No
- What would you think if the bot incorporated gifs and memes within the conversation?
    - Good depending on mood

- Do you have any further questions for us?
    - When will it be released

**Comment by thejoefriel** [comment]
# User 4:
year 10
male
related apps: social media
used chatbot like this before? yes
happy talking to bots: no, probably would just talk to somebody. Concerned that the bot would share data / read his info

### USER FLOW 1:

### Task 1
Please can you register on the app.
    - no issues
    - initial conversation covers privacy issues so he was happy with that wording

### Task 2
Can you please see a breakdown of your moods over the past 30 days. 
    - no issues

### Task 3
Now can you have a conversation with the nightingale chatbot.
    - helpful conversation flow

### Task 4
Finally please log out


## Follow Up Questions

- How did you find using the application?
    - easy to use
    - good app for talking about feelings and getting advice
    - would go straight to advice sometimes rather than deal with the chat

- Did you have any other observations that you’d like to share?
    - No

- Have you used any similar platforms or applications before?
    - No

- What would you think if the bot incorporated gifs and memes within the conversation?
    - yes would be more fun

- Do you have any further questions for us?
    - No
