### ISSUE TITLE
Static-Components

### ISSUE THREAD

**Issue by AsalaKM** [techforbetter/nightingale#53]
- [x] menu
- [x] logo
- [x] header
- [x] chart
- [x] button
- [x] title
- [x] formInput

**Comment by thejoefriel** [comment]
Hey @AsalaKM - sorry what do you mean with this issue? Is it the icons that we'll be using and some common styled components?

**Comment by thejoefriel** [comment]
Oh also @AsalaKM do you mind adding any issue to the Project Plan under projects please :) It's just so we don't then miss any issues and can see what's in progress
