### ISSUE TITLE
list of example chatbot apps

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/nightingale#9]
Please list any apps that might be useful for us to look into in terms of user flow, design, logic...

**Comment by dupreesi** [comment]
VentBot was a grad project at FAC 14 using Dialogflow a natural language processing API that we trained to recognise common 'intents' such as loneliness, conflict and sadness
https://vent-bot.herokuapp.com/

**Comment by dupreesi** [comment]
WYSA 
chatbot that covers stress, anxiety and mindfulness. It asks you questions (open and selective), stores your data and gives you advice in terms of exercises. it uses the giphy api and its generally very appealing. They do not use a dashboard but only a navbar that enables you to hit the various options. I think that its a good idea as dashboards often harm the user flow if there are only few options etc.

**Comment by dupreesi** [comment]
Woebot
https://woebot.io/
-[x] nice clear design
-[x] first 3 cards explaining what the app is about -> then register with name and pw -> then register via chatbot
-[x] register uses almost pre-defined answers (yes, no, agree, not sure..) 
-[x] asks you what time it should check in again with you
-[x] also uses giphy to create fun answers

**Comment by RamyAlshurafa** [comment]
https://vimeo.com/161016937
https://vimeo.com/161016939
videos for how onboarding could be.
